// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rl_bl.Context;

namespace kubaapi.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20190318200230_addTestungData3")]
    partial class addTestungData3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kubaapi.Models.Patient", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime?>("AnamneseDate");

                    b.Property<bool?>("AnamnesePayed");

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("Birthday");

                    b.Property<DateTime?>("DiagnostikDate");

                    b.Property<bool?>("DiagnostikPayed");

                    b.Property<DateTime?>("ElternDate");

                    b.Property<bool?>("ElternPayed");

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<string>("ProblemHierarchy");

                    b.Property<string>("Tele");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new { Id = 1, Birthday = new DateTime(1988, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), Firstname = "Kleiner", Lastname = "Hase", Tele = "0177123456" },
                        new { Id = 2, Birthday = new DateTime(1988, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), Firstname = "Stefan", Lastname = "Parge", Tele = "0177123457" }
                    );
                });

            modelBuilder.Entity("kubaapi.Models.Review", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Exercises");

                    b.Property<string>("Name");

                    b.Property<int?>("PatientId");

                    b.Property<bool>("Payed");

                    b.Property<string>("Reasons");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new { Id = 1, Date = new DateTime(2019, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), Exercises = "Liegestütze und dann Kaffee trinken", Name = "Befundgespräch", PatientId = 1, Payed = true, Reasons = "Das war dringend notwendig" },
                        new { Id = 2, Date = new DateTime(2019, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), Exercises = "Liegestütze und dann Kaffee trinken", Name = "1. Review", PatientId = 1, Payed = true, Reasons = "Das war dringend notwendig" },
                        new { Id = 3, Date = new DateTime(2019, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), Exercises = "Liegestütze und dann Kaffee trinken", Name = "2. Review", PatientId = 1, Payed = false, Reasons = "Das war dringend notwendig" },
                        new { Id = 4, Date = new DateTime(2019, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), Exercises = "Liegestütze und dann Kaffee trinken", Name = "Befundgespräch", PatientId = 2, Payed = true, Reasons = "Das war dringend notwendig" },
                        new { Id = 5, Date = new DateTime(2019, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), Exercises = "Liegestütze und dann Kaffee trinken", Name = "1. Review", PatientId = 2, Payed = false, Reasons = "Das war dringend notwendig" },
                        new { Id = 6, Date = new DateTime(2019, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), Exercises = "Liegestütze und dann Kaffee trinken", Name = "2. Review", PatientId = 2, Payed = false, Reasons = "Das war dringend notwendig" }
                    );
                });

            modelBuilder.Entity("kubaapi.Models.Testung", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<int?>("PatientId");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasFilter("[PatientId] IS NOT NULL");

                    b.ToTable("Testungen");

                    b.HasData(
                        new { Id = 1, Date = new DateTime(2019, 3, 18, 21, 2, 30, 413, DateTimeKind.Local), Name = "Erste Testung", PatientId = 1 }
                    );
                });

            modelBuilder.Entity("kubaapi.Models.TestungChapter", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("TestungId");

                    b.HasKey("Id");

                    b.HasIndex("TestungId");

                    b.ToTable("TestungChapters");

                    b.HasData(
                        new { Id = 1, Name = "I. TESTS ZUR ÜBERPRÜFUNG DER GROBMOTORISCHEN KOORDINAION UND DES GLEICHGEWICHTS", TestungId = 1 },
                        new { Id = 2, Name = "II. TESTS ZUR MOTORISCHEN ENTWICKLUNG", TestungId = 1 },
                        new { Id = 3, Name = "III. TESTS ZUR ÜBERPRÜFUNG VON KLEINHIRNFUNKTIONEN", TestungId = 1 }
                    );
                });

            modelBuilder.Entity("kubaapi.Models.TestungQuestion", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label");

                    b.Property<int?>("TestungChapterId");

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("TestungChapterId");

                    b.ToTable("TestungQuestions");

                    b.HasData(
                        new { Id = 1, Label = "Aufrichten aus Rückenlage in den Stand", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 2, Label = "Aufrichten aus Bauchlage in den Stand", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 3, Label = "Romberg Test (Augen geöffnet)", TestungChapterId = 1, Type = "radio", Value = "" },
                        new { Id = 4, Label = "Tandem Gang (rückwärts)", TestungChapterId = 1, Type = "radio", Value = "" }
                    );
                });

            modelBuilder.Entity("kubaapi.Models.Review", b =>
                {
                    b.HasOne("kubaapi.Models.Patient")
                        .WithMany("Reviews")
                        .HasForeignKey("PatientId");
                });

            modelBuilder.Entity("kubaapi.Models.Testung", b =>
                {
                    b.HasOne("kubaapi.Models.Patient")
                        .WithOne("Testung")
                        .HasForeignKey("kubaapi.Models.Testung", "PatientId");
                });

            modelBuilder.Entity("kubaapi.Models.TestungChapter", b =>
                {
                    b.HasOne("kubaapi.Models.Testung")
                        .WithMany("Chapters")
                        .HasForeignKey("TestungId");
                });

            modelBuilder.Entity("kubaapi.Models.TestungQuestion", b =>
                {
                    b.HasOne("kubaapi.Models.TestungChapter")
                        .WithMany("Questions")
                        .HasForeignKey("TestungChapterId");
                });
#pragma warning restore 612, 618
        }
    }
}
